[CI] Add Canadian build

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -26,6 +26,7 @@ jobs:
           - 'armv6-rpi-linux-gnueabihf'
           - 'armv8-rpi3-linux-gnueabihf'
           - 'arm-pico-eabi'
+          - 'arm-pico2-eabi'
         gcc-version:
           - '12'
           - '13'
@@ -74,6 +75,7 @@ jobs:
         id: build
         uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
         with:
+          pull: true
           context: .
           target: gcc-build
           build-args: |
@@ -137,3 +139,79 @@ jobs:
           push: ${{ github.event_name != 'pull_request' }}
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+
+  build-arm64:
+    needs: build
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+      packages: write
+    strategy:
+      matrix:
+        triple:
+          - 'aarch64-rpi3-linux-gnu'
+          - 'armv6-rpi-linux-gnueabihf'
+          - 'armv8-rpi3-linux-gnueabihf'
+          - 'arm-pico-eabi'
+          - 'arm-pico2-eabi'
+        gcc-version:
+          - '12'
+          - '13'
+          - '14'
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf
+
+      # Workaround: https://github.com/docker/build-push-action/issues/461
+      - name: Setup Docker buildx
+        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb
+
+      # Build and load Docker image with Buildx
+      # https://github.com/docker/build-push-action
+      - name: Build and load Docker image
+        id: build
+        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
+        with:
+          pull: true
+          context: .
+          platforms: linux/arm64/v8
+          target: gcc-build-canadian
+          build-args: |
+            TARGET_TRIPLE=${{ matrix.triple }}
+            HOST_TRIPLE=aarch64-rpi3-linux-gnu
+            GCC_VERSION=${{ matrix.gcc-version }}
+          load: true
+          tags: ${{ env.TEMPORARY_TAG }}-canadian
+          cache-from: |
+            type=gha,scope=aarch64-rpi3-linux-gnu-gcc${{ matrix.gcc-version }}
+            type=gha,scope=aarch64-rpi3-linux-gnu-${{ matrix.triple }}-gcc${{ matrix.gcc-version }}
+          cache-to: type=gha,mode=max,scope=aarch64-rpi3-linux-gnu-${{ matrix.triple }}-gcc${{ matrix.gcc-version }}
+
+      # Archive the toolchain in the Docker container and copy it to the build environment
+      - name: Export toolchain
+        run: |
+          container=$(docker run -d ${{ env.TEMPORARY_TAG }}-canadian \
+              bash -c "tar cJf x-tools.tar.xz x-tools")
+          status=$(docker wait $container)
+          if [ $status -ne 0 ]; then
+              echo "Error creating toolchain archives"
+              exit 1
+          fi
+          echo "Copying toolchain from Docker container to host"
+          docker cp $container:/home/develop/x-tools.tar.xz x-tools-aarch64-rpi3-linux-gnu-${{ matrix.triple }}-gcc${{ matrix.gcc-version }}.tar.xz
+          docker rm $container
+
+      - name: Upload toolchain
+        uses: actions/upload-artifact@v4
+        with:
+          name: x-tools-aarch64-rpi3-linux-gnu-${{ matrix.triple }}-gcc${{ matrix.gcc-version }}
+          path: x-tools-aarch64-rpi3-linux-gnu-${{ matrix.triple }}-gcc${{ matrix.gcc-version }}.tar.xz
+
+      - name: Release toolchain
+        if: ${{ github.event.action == 'released' || github.event.action == 'prereleased' }}
+        uses: softprops/action-gh-release@17cd0d34deddf848fc0e7d9be5202c148c270a0a
+        with:
+          files: x-tools-aarch64-rpi3-linux-gnu-${{ matrix.triple }}-gcc${{ matrix.gcc-version }}.tar.xz
